onlineclass/onlineclass/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('classroom.urls', namespace='classroom')),
    path('student/', include('student.urls', namespace='student')),
]

onlineclass/student/urls.py
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
    path('signup', views.signup_view, name='signup_view'), 
    path('login', views.login_view, name='login_view'),
    path('logout', views.logout_view, name='logout_view'),
    path('my_classes', views.my_classes, name='my_classes'),
    # path('my_questions', views.my_questions, name='my_questions'),
    # path('questions/<int:id>/edit', views.update_question, name='update_question'),
    # path('questions/<int:id>/delete', views.delete_question, name='delete_question'),
    # path('questions/<int:id>/answers', views.get_answers, name='get_answers'),
    # path('questions/<int:id>/answers/add', views.post_answer, name='post_answer'),
    # path('my_answers', views.my_answers, name='my_answers'),
    # path('answers/<int:id>/edit', views.update_answer, name='update_answer'),
    # path('answers/<int:id>/delete', views.delete_answer, name='delete_answer'),
    # path('question/tag/<slug>', views.tag_result, name='tag_result'),
    # path('search', views.search, name='search'),
    # path('download_json_data', views.download_json_data, name='download_json_data'),
    # path('tags', views.all_tags, name='all_tags'),


]

onlineclass/templates/base.html
{% load static %}
<html lang="en">

  ​
  
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> SHIKSHALAY </title>
    
      <script
  
      src="https://code.jquery.com/jquery-1.12.4.min.js"
  
      integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
  
      crossorigin="anonymous"></script>
  
      
  
      <script src="https://code.highcharts.com/highcharts.src.js"></script>
  
  ​
  
      <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  
  ​
  
      <title>Expense App</title>
  
  ​
  
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  
            integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  
      
  
      <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
  
            integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  
      
  
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  
              integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  
              crossorigin="anonymous"></script>
  
      
  
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
  
              integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
  
              crossorigin="anonymous"></script>
  
      
  
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
  
              integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
  
              crossorigin="anonymous"></script>  
  ​<style>
    .navbar {
    margin-top: -25;
    position: relative;
    display: flex;
    align-items: center;
    padding: .5rem 2rem;
    }
   
    body{
      height: 900px;
      }

      .image{

background-image: url("https://ak.picdn.net/shutterstock/videos/26388761/thumb/1.jpg");
background-repeat: no-repeat;
height:120%;
background-position: center;
background-repeat: no-repeat;
background-size: cover;
display: flex;
flex-wrap: wrap;
padding-top: 3vh;
}  
footer {
    display: block;
    background-color:rgb(66, 64, 64);
    color:gainsboro;
    }
{% block style %}
{% endblock style%}    
</style>   
</head>
  <body>
    
      {% if messages %}
  
          {% for msg in messages %}
  
              <div class="alert alert-info alert-dismissable">
  
                  {{msg.message}}
  
              </div>
  
          {% endfor %}
  
      {% endif %}
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">SHIKSHALAY</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% if not user.is_anonymous %}
            <li class="nav-item">
              <a class="nav-link" href="#">Hi {{user}}</a>
            </li>
            {% endif %}
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'student:my_classes' %}">My Classes</a>
              </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'student:logout_view' %}">Logout</a>
            </li>
            {% endif %}
            {% if user.is_anonymous %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'student:login_view' %}">Login</a>
            </li>            
            <li class="nav-item">
              <a class="nav-link" href="{% url 'student:signup_view' %}">Signup</a>
            </li>
            {% endif %}
            
            
          </ul>
          
        </div>
      </nav>
      <div class="image">
      {% block body %}
      {% endblock %}  ​
      </div>
  
</body>
<footer class="page-footer font-small black">
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="#"> SHIKSHALAY</a>
  </div>
</footer>
</html>