onlineclass/classroom/urls.py
from django.urls import path
from . import views

app_name = 'cr'

urlpatterns = [
    path('', views.home, name='home'),
    path('classroom/<int:id>', views.class_details, name = 'class_details'),
    path('classroom/<int:id>/register', views.register, name = 'register'),
    path('classroom/<int:id>/register_cancel', views.register_cancel, name = 'register_cancel'),
]

onlineclass/onlineclass/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('classroom.urls', namespace='classroom')),
    path('student/', include('student.urls', namespace='student')),
]

onlineclass/student/urls.py
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
    path('signup', views.signup_view, name='signup_view'), 
    path('login', views.login_view, name='login_view'),
    path('logout', views.logout_view, name='logout_view'),
    path('my_classes', views.my_classes, name='my_classes'),
    # path('my_questions', views.my_questions, name='my_questions'),
    # path('questions/<int:id>/edit', views.update_question, name='update_question'),
    # path('questions/<int:id>/delete', views.delete_question, name='delete_question'),
    # path('questions/<int:id>/answers', views.get_answers, name='get_answers'),
    # path('questions/<int:id>/answers/add', views.post_answer, name='post_answer'),
    # path('my_answers', views.my_answers, name='my_answers'),
    # path('answers/<int:id>/edit', views.update_answer, name='update_answer'),
    # path('answers/<int:id>/delete', views.delete_answer, name='delete_answer'),
    # path('question/tag/<slug>', views.tag_result, name='tag_result'),
    # path('search', views.search, name='search'),
    # path('download_json_data', views.download_json_data, name='download_json_data'),
    # path('tags', views.all_tags, name='all_tags'),


]

onlineclass/classroom/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
# Create your models here.
CLASS_CHOICES = ( 
    ("V", "V"), 
    ("VI", "VI"), 
    ("VII", "VII"), 
    ("VIII", "VIII"), 
    ("IX", "IX"), 
    ("X", "X"), 
    ("XI", "XI"), 
    ("X", "X"), 
)
class User(AbstractUser):

    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)


class Classroom(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room_name = models.CharField(max_length=20)
    subject = models.CharField(max_length=25)
    standard = models.CharField(max_length = 4, 
        choices = CLASS_CHOICES, 
        default = 'V'
        )
    description = models.TextField()
     
    class Meta:
        verbose_name = 'Classroom'
        verbose_name_plural = 'Classrooms'

    def __str__(self):
         return self.room_name

onlineclass/classroom/views.py
from django.shortcuts import render, redirect
from .models import Classroom
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages

# Create your views here.
def home(request):
    """
    Url to home page.

    :http relative-url: /
    :http-method : GET
    """
    classes = Classroom.objects.all()
    context = {'classes': classes}
    template = 'home.html'
    return render(request, template, context)

def class_details(request, id):
    """
    Url to class detail page.

    :http relative-url: /classroom/<id>
    :http-method : GET
    """
    class_details = Classroom.objects.get(id=id)
    template = 'class_details.html'
    context = {'class_details':class_details}
    return render(request, template, context)

@login_required(login_url="/student/login/")
def register(request, id):
    """
    Url to register to a classroom.

    :http relative-url: /classroom/<id>
    :http-method : POST
    """
    user = request.user
    classroom = Classroom.objects.get(id=id)
    if classroom:
        if user not in classroom.student_set.all():
            user.student.classes.add(classroom)
            send_mail('Registration Successful', 'Dear '+user.student.name+', you have successfully registered to '+classroom.room_name+' course. Please find the details from the website.',
            settings.EMAIL_HOST_USER,[user.email],fail_silently=False
            )
            messages.success(request, "Registration Successful")
        else:
            messages.error(request, "ALready registered to this course")
    else:
        messages.error(request, "Could not find the classroom you were looking for.")
    return redirect('student:my_classes')

@login_required(login_url="/student/login/")
def register_cancel(request, id):
    """
    Url to cancel registration.
    :http relative-url: /classroom/<id>
    :http-method : POST
    """

    user = request.user
    classroom = Classroom.objects.get(id=id)
    if classroom:
        user.student.classes.remove(classroom)
        send_mail('Registration Cancelled', 'Dear '+user.student.name+', you have successfully registered to '+classroom.room_name+' course. Please find the details from the website.',
            settings.EMAIL_HOST_USER,[user.email],fail_silently=False
            )
        messages.success(request, "Registration cancelled")
    else:
        messages.error(request, "Could not find the classroom you were looking for.")
    return redirect('student:my_classes')

onlineclass/classroom/templates/class_details.html
{% extends 'base.html' %}
{% block body %}
<br>
<script type="text/javascript">
    function showMessage(){
      alert("Do you want to register?");
    }
    function showMessage2(){
      alert("Do you want to cancel this registration?");
    }
  </script>
        <div class="col-sm-4">
            <div class="card text-center">
                <div class="card-header">
                    <h4 class="mt-6 text-center">class:  {{class_details.room_name}}</h4>
                </div>
                <div class="card-body">
                    <h5 class="card-title">Description:  {{class_details.subject}} for class {{class_details.standard}}</h5>
                    <p class="card-text text-muted">  {{class_details.description}}</p>
                    {% if user.is_authenticated and class_details not in user.student.classes.all %}
                    <form action="{% url 'cr:register' class_details.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary" onCLick=showMessage()>Register</button>
                    </form>
                    {% elif user.is_authenticated and class_details in user.student.classes.all%}
                    <form action="{% url 'cr:register_cancel' class_details.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary" onCLick=showMessage2()>Cancel Registration</button>
                    </form>                    <br>
                    {% endif %}
                </div>
               
            </div>
        </div>
    <br>
    <br>
{% endblock %}

onlineclass/classroom/templates/home.html
{% extends 'base.html' %}
{% block body %}
<br>
{% if classes %}

    {% for each_class in classes %}
    <!-- <div class="row"> -->
        
        <div class="col-sm-4">
            <div class="card text-center">
                <div class="card-header">
                    <h4 class="mt-6 text-center">Classroom name:  {{each_class.room_name}}</h4>
                </div>
                <div class="card-body">
                    <h5 class="card-title">Description:  {{each_class.subject}} for class {{each_class.standard}}</h5>
                    <p class="card-text text-muted">by  {{each_class.user.username}}</p>
                    <a href="{% url 'cr:class_details' each_class.id %}" class="btn btn-primary">Class Details</a>
                    
                </div>
                
            </div>
        </div>

  {% endfor %}
  
  {% else %}
    No classes
    {% endif %}

{% endblock %}

   